BEGIN TRANSACTION
CREATE TABLE [t_individuals] ([Individualguid] nvarchar(255) NOT NULL PRIMARY KEY, [IndividualID] nvarchar(255) NOT NULL, [FamilyName] nvarchar(255) NULL, [GivenName] nvarchar(255) NULL, [ConcatenatedName] nvarchar(255) NULL, [RegistrationDate] nvarchar(255) NULL, [DateofBirth] nvarchar(255) NULL, [CountryOfOrigin] nvarchar(255) NULL, [AsylumCountryCode] nvarchar(255) NULL, [ArrivalDate] nvarchar(255) NULL, [gender] nvarchar(255) NULL, [Age] nvarchar(255) NULL, [IndividualAgeCohortCode] nvarchar(255) NULL, [NationalityCode] nvarchar(255) NULL, [RSDStatusCode] nvarchar(255) NULL, [ResettlementStatusCode] nvarchar(255) NULL, [VolRepStatusCode] nvarchar(255) NULL, [MarriageStatusCode] nvarchar(255) NULL, [EthnicityCode] nvarchar(255) NULL, [EducationLevelCode] nvarchar(255) NULL, [OccupationCode] nvarchar(255) NULL, [ProcessStatusCode] nvarchar(255) NULL, [RefugeeStatusCode] nvarchar(255) NULL, [FatherName] nvarchar(255) NULL, [MotherName] nvarchar(255) NULL, [SiteIDOwner] nvarchar(255) NULL, [SiteIDCreate] nvarchar(255) NULL, [CreateDate] nvarchar(255) NULL, [IsAnyGroupPrincipalRepresentative] nvarchar(255) NULL, [HasSPNeed] nvarchar(255) NULL, [RelationshipText] nvarchar(255) NULL, [PrincipalRepresentative] nvarchar(255) NULL, [RelationshipToPrincipalRepresentative] nvarchar(255) NULL);
CREATE TABLE [base_data] ([IndividualID] nvarchar(255) NOT NULL PRIMARY KEY, [Individualguid] nvarchar(255) NULL, [FamilyName] nvarchar(255) NULL, [GivenName] nvarchar(255) NULL, [ConcatenatedName] nvarchar(255) NULL, [RegistrationDate] nvarchar(255) NULL, [DateofBirth] nvarchar(255) NULL, [CountryOfOrigin] nvarchar(255) NULL, [AsylumCountryCode] nvarchar(255) NULL, [ArrivalDate] nvarchar(255) NULL, [gender] nvarchar(255) NULL, [Age] nvarchar(255) NULL, [IndividualAgeCohortCode] nvarchar(255) NULL, [NationalityCode] nvarchar(255) NULL, [RSDStatusCode] nvarchar(255) NULL, [ResettlementStatusCode] nvarchar(255) NULL, [VolRepStatusCode] nvarchar(255) NULL, [MarriageStatusCode] nvarchar(255) NULL, [EthnicityCode] nvarchar(255) NULL, [EducationLevelCode] nvarchar(255) NULL, [OccupationCode] nvarchar(255) NULL, [ProcessStatusCode] nvarchar(255) NULL, [RefugeeStatusCode] nvarchar(255) NULL, [FatherName] nvarchar(255) NULL, [MotherName] nvarchar(255) NULL, [SiteIDOwner] nvarchar(255) NULL, [SiteIDCreate] nvarchar(255) NULL, [CreateDate] nvarchar(255) NULL, [IsAnyGroupPrincipalRepresentative] nvarchar(255) NULL, [HasSPNeed] nvarchar(255) NULL, [ProcessingGroupTypeCode] nvarchar(255) NULL, [ProcessingGroupNumber] nvarchar(255) NULL, [CurrentRationCardNumber] nvarchar(255) NULL, [ProcessingGroupFileNumber] nvarchar(255) NULL, [ProcessingGroupSize] nvarchar(255) NULL, [ProcessingGroupStatusCode] nvarchar(255) NULL, [ProcessGroupStatusDate] nvarchar(255) NULL, [ProcessingGroupRegistrationDate] nvarchar(255) NULL, [IndividualSequenceNumber] nvarchar(255) NULL, [PrincipalRepresentative] nvarchar(255) NULL, [RelationshipToPrincipalRepresentative] nvarchar(255) NULL, [RelationshipText] nvarchar(255) NULL, [COALocationLevel1ID] nvarchar(255) NULL, [COALocationLevel2ID] nvarchar(255) NULL, [COALocationLevel3ID] nvarchar(255) NULL, [COALocationLevel4ID] nvarchar(255) NULL, [COALocationLevel5ID] nvarchar(255) NULL, [COOLocationLevel1ID] nvarchar(255) NULL, [COOLocationLevel2ID] nvarchar(255) NULL, [COOLocationLevel3ID] nvarchar(255) NULL, [COOLocationLevel4ID] nvarchar(255) NULL, [COOLocationLevel5ID] nvarchar(255) NULL, [VulnerabilityCode] nvarchar(255) NULL, [VulnerabilityDetailsCode] nvarchar(255) NULL);
CREATE TABLE [t_coa_address] ([id] int IDENTITY (1, 1) NOT NULL PRIMARY KEY, [COALocationLevel1ID] nvarchar(255) NULL, [COALocationLevel2ID] nvarchar(255) NULL, [COALocationLevel3ID] nvarchar(255) NULL, [COALocationLevel4ID] nvarchar(255) NULL, [COALocationLevel5ID] nvarchar(255) NULL, [fkindividualguid_id] nvarchar(255) NOT NULL);
CREATE TABLE [t_coo_address] ([id] int IDENTITY (1, 1) NOT NULL PRIMARY KEY, [COOLocationLevel1ID] nvarchar(255) NULL, [COOLocationLevel2ID] nvarchar(255) NULL, [COOLocationLevel3ID] nvarchar(255) NULL, [COOLocationLevel4ID] nvarchar(255) NULL, [COOLocationLevel5ID] nvarchar(255) NULL, [fkindividualguid_id] nvarchar(255) NOT NULL);
CREATE TABLE [t_group] ([id] int IDENTITY (1, 1) NOT NULL PRIMARY KEY, [ProcessingGroupTypeCode] nvarchar(255) NULL, [ProcessingGroupNumber] nvarchar(255) NULL, [CurrentRationCardNumber] nvarchar(255) NULL, [ProcessingGroupFileNumber] nvarchar(255) NULL, [ProcessingGroupSize] nvarchar(255) NULL, [ProcessingGroupStatusCode] nvarchar(255) NULL, [ProcessGroupStatusDate] nvarchar(255) NULL, [ProcessingGroupRegistrationDate] nvarchar(255) NULL, [IndividualSequenceNumber] nvarchar(255) NULL, [fkindividualguid_id] nvarchar(255) NOT NULL);
CREATE TABLE [t_vuln_status] ([id] int IDENTITY (1, 1) NOT NULL PRIMARY KEY, [VulnerabilityCode] nvarchar(255) NULL, [VulnerabilityDetailsCode] nvarchar(255) NULL, [fkindividualguid_id] nvarchar(255) NOT NULL);
ALTER TABLE [t_coa_address] ADD CONSTRAINT [t_coa_address_fkindividualguid_id_3613104f_fk_t_individuals_Individualguid] FOREIGN KEY ([fkindividualguid_id]) REFERENCES [t_individuals] ([Individualguid]);
CREATE INDEX [t_coa_address_2ad12d3e] ON [t_coa_address] ([fkindividualguid_id]);
ALTER TABLE [t_coo_address] ADD CONSTRAINT [t_coo_address_fkindividualguid_id_6dae4eb9_fk_t_individuals_Individualguid] FOREIGN KEY ([fkindividualguid_id]) REFERENCES [t_individuals] ([Individualguid]);
CREATE INDEX [t_coo_address_2ad12d3e] ON [t_coo_address] ([fkindividualguid_id]);
ALTER TABLE [t_group] ADD CONSTRAINT [t_group_fkindividualguid_id_536466d6_fk_t_individuals_Individualguid] FOREIGN KEY ([fkindividualguid_id]) REFERENCES [t_individuals] ([Individualguid]);
CREATE INDEX [t_group_2ad12d3e] ON [t_group] ([fkindividualguid_id]);
ALTER TABLE [t_vuln_status] ADD CONSTRAINT [t_vuln_status_fkindividualguid_id_1b3ad603_fk_t_individuals_Individualguid] FOREIGN KEY ([fkindividualguid_id]) REFERENCES [t_individuals] ([Individualguid]);
CREATE INDEX [t_vuln_status_2ad12d3e] ON [t_vuln_status] ([fkindividualguid_id]);

COMMIT;
