# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseData',
            fields=[
                ('individualguid', models.CharField(max_length=255, serialize=False, primary_key=True, db_column='Individualguid')),
                ('individualid', models.CharField(max_length=255, db_column='IndividualID', blank=True)),
                ('familyname', models.CharField(max_length=255, null=True, db_column='FamilyName', blank=True)),
                ('givenname', models.CharField(max_length=255, null=True, db_column='GivenName', blank=True)),
                ('concatenatedname', models.CharField(max_length=255, null=True, db_column='ConcatenatedName', blank=True)),
                ('registrationdate', models.CharField(max_length=255, null=True, db_column='RegistrationDate', blank=True)),
                ('dateofbirth', models.CharField(max_length=255, null=True, db_column='DateofBirth', blank=True)),
                ('countryoforigin', models.CharField(max_length=255, null=True, db_column='CountryOfOrigin', blank=True)),
                ('asylumcountrycode', models.CharField(max_length=255, null=True, db_column='AsylumCountryCode', blank=True)),
                ('arrivaldate', models.CharField(max_length=255, null=True, db_column='ArrivalDate', blank=True)),
                ('gender', models.CharField(max_length=255, null=True, blank=True)),
                ('age', models.CharField(max_length=255, null=True, db_column='Age', blank=True)),
                ('individualagecohortcode', models.CharField(max_length=255, null=True, db_column='IndividualAgeCohortCode', blank=True)),
                ('nationalitycode', models.CharField(max_length=255, null=True, db_column='NationalityCode', blank=True)),
                ('rsdstatuscode', models.CharField(max_length=255, null=True, db_column='RSDStatusCode', blank=True)),
                ('resettlementstatuscode', models.CharField(max_length=255, null=True, db_column='ResettlementStatusCode', blank=True)),
                ('volrepstatuscode', models.CharField(max_length=255, null=True, db_column='VolRepStatusCode', blank=True)),
                ('marriagestatuscode', models.CharField(max_length=255, null=True, db_column='MarriageStatusCode', blank=True)),
                ('ethnicitycode', models.CharField(max_length=255, null=True, db_column='EthnicityCode', blank=True)),
                ('educationlevelcode', models.CharField(max_length=255, null=True, db_column='EducationLevelCode', blank=True)),
                ('occupationcode', models.CharField(max_length=255, null=True, db_column='OccupationCode', blank=True)),
                ('processstatuscode', models.CharField(max_length=255, null=True, db_column='ProcessStatusCode', blank=True)),
                ('refugeestatuscode', models.CharField(max_length=255, null=True, db_column='RefugeeStatusCode', blank=True)),
                ('fathername', models.CharField(max_length=255, null=True, db_column='FatherName', blank=True)),
                ('mothername', models.CharField(max_length=255, null=True, db_column='MotherName', blank=True)),
                ('siteidowner', models.CharField(max_length=255, null=True, db_column='SiteIDOwner', blank=True)),
                ('siteidcreate', models.CharField(max_length=255, null=True, db_column='SiteIDCreate', blank=True)),
                ('createdate', models.CharField(max_length=255, null=True, db_column='CreateDate', blank=True)),
                ('isanygroupprincipalrepresentative', models.CharField(max_length=255, null=True, db_column='IsAnyGroupPrincipalRepresentative', blank=True)),
                ('hasspneed', models.CharField(max_length=255, null=True, db_column='HasSPNeed', blank=True)),
                ('relationshiptext', models.CharField(max_length=255, null=True, db_column='RelationshipText', blank=True)),
                ('principalrepresentative', models.CharField(max_length=255, null=True, db_column='PrincipalRepresentative', blank=True)),
                ('relationshiptoprincipalrepresentative', models.CharField(max_length=255, null=True, db_column='RelationshipToPrincipalRepresentative', blank=True)),
            ],
            options={
                'db_table': 't_individuals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BaseDataBdi',
            fields=[
                ('individualid', models.CharField(max_length=255, serialize=False, primary_key=True, db_column='IndividualID', blank=True)),
                ('individualguid', models.CharField(max_length=255, null=True, db_column='Individualguid', blank=True)),
                ('familyname', models.CharField(max_length=255, null=True, db_column='FamilyName', blank=True)),
                ('givenname', models.CharField(max_length=255, null=True, db_column='GivenName', blank=True)),
                ('concatenatedname', models.CharField(max_length=255, null=True, db_column='ConcatenatedName', blank=True)),
                ('registrationdate', models.CharField(max_length=255, null=True, db_column='RegistrationDate', blank=True)),
                ('dateofbirth', models.CharField(max_length=255, null=True, db_column='DateofBirth', blank=True)),
                ('countryoforigin', models.CharField(max_length=255, null=True, db_column='CountryOfOrigin', blank=True)),
                ('asylumcountrycode', models.CharField(max_length=255, null=True, db_column='AsylumCountryCode', blank=True)),
                ('arrivaldate', models.CharField(max_length=255, null=True, db_column='ArrivalDate', blank=True)),
                ('gender', models.CharField(max_length=255, null=True, blank=True)),
                ('age', models.CharField(max_length=255, null=True, db_column='Age', blank=True)),
                ('individualagecohortcode', models.CharField(max_length=255, null=True, db_column='IndividualAgeCohortCode', blank=True)),
                ('nationalitycode', models.CharField(max_length=255, null=True, db_column='NationalityCode', blank=True)),
                ('rsdstatuscode', models.CharField(max_length=255, null=True, db_column='RSDStatusCode', blank=True)),
                ('resettlementstatuscode', models.CharField(max_length=255, null=True, db_column='ResettlementStatusCode', blank=True)),
                ('volrepstatuscode', models.CharField(max_length=255, null=True, db_column='VolRepStatusCode', blank=True)),
                ('marriagestatuscode', models.CharField(max_length=255, null=True, db_column='MarriageStatusCode', blank=True)),
                ('ethnicitycode', models.CharField(max_length=255, null=True, db_column='EthnicityCode', blank=True)),
                ('educationlevelcode', models.CharField(max_length=255, null=True, db_column='EducationLevelCode', blank=True)),
                ('occupationcode', models.CharField(max_length=255, null=True, db_column='OccupationCode', blank=True)),
                ('processstatuscode', models.CharField(max_length=255, null=True, db_column='ProcessStatusCode', blank=True)),
                ('refugeestatuscode', models.CharField(max_length=255, null=True, db_column='RefugeeStatusCode', blank=True)),
                ('fathername', models.CharField(max_length=255, null=True, db_column='FatherName', blank=True)),
                ('mothername', models.CharField(max_length=255, null=True, db_column='MotherName', blank=True)),
                ('siteidowner', models.CharField(max_length=255, null=True, db_column='SiteIDOwner', blank=True)),
                ('siteidcreate', models.CharField(max_length=255, null=True, db_column='SiteIDCreate', blank=True)),
                ('createdate', models.CharField(max_length=255, null=True, db_column='CreateDate', blank=True)),
                ('isanygroupprincipalrepresentative', models.CharField(max_length=255, null=True, db_column='IsAnyGroupPrincipalRepresentative', blank=True)),
                ('hasspneed', models.CharField(max_length=255, null=True, db_column='HasSPNeed', blank=True)),
                ('processinggrouptypecode', models.CharField(max_length=255, null=True, db_column='ProcessingGroupTypeCode', blank=True)),
                ('processinggroupnumber', models.CharField(max_length=255, null=True, db_column='ProcessingGroupNumber', blank=True)),
                ('currentrationcardnumber', models.CharField(max_length=255, null=True, db_column='CurrentRationCardNumber', blank=True)),
                ('processinggroupfilenumber', models.CharField(max_length=255, null=True, db_column='ProcessingGroupFileNumber', blank=True)),
                ('processinggroupsize', models.CharField(max_length=255, null=True, db_column='ProcessingGroupSize', blank=True)),
                ('processinggroupstatuscode', models.CharField(max_length=255, null=True, db_column='ProcessingGroupStatusCode', blank=True)),
                ('processgroupstatusdate', models.CharField(max_length=255, null=True, db_column='ProcessGroupStatusDate', blank=True)),
                ('processinggroupregistrationdate', models.CharField(max_length=255, null=True, db_column='ProcessingGroupRegistrationDate', blank=True)),
                ('individualsequencenumber', models.CharField(max_length=255, null=True, db_column='IndividualSequenceNumber', blank=True)),
                ('principalrepresentative', models.CharField(max_length=255, null=True, db_column='PrincipalRepresentative', blank=True)),
                ('relationshiptoprincipalrepresentative', models.CharField(max_length=255, null=True, db_column='RelationshipToPrincipalRepresentative', blank=True)),
                ('relationshiptext', models.CharField(max_length=255, null=True, db_column='RelationshipText', blank=True)),
                ('coalocationlevel1id', models.CharField(max_length=255, null=True, db_column='COALocationLevel1ID', blank=True)),
                ('coalocationlevel2id', models.CharField(max_length=255, null=True, db_column='COALocationLevel2ID', blank=True)),
                ('coalocationlevel3id', models.CharField(max_length=255, null=True, db_column='COALocationLevel3ID', blank=True)),
                ('coalocationlevel4id', models.CharField(max_length=255, null=True, db_column='COALocationLevel4ID', blank=True)),
                ('coalocationlevel5id', models.CharField(max_length=255, null=True, db_column='COALocationLevel5ID', blank=True)),
                ('coolocationlevel1id', models.CharField(max_length=255, null=True, db_column='COOLocationLevel1ID', blank=True)),
                ('coolocationlevel2id', models.CharField(max_length=255, null=True, db_column='COOLocationLevel2ID', blank=True)),
                ('coolocationlevel3id', models.CharField(max_length=255, null=True, db_column='COOLocationLevel3ID', blank=True)),
                ('coolocationlevel4id', models.CharField(max_length=255, null=True, db_column='COOLocationLevel4ID', blank=True)),
                ('coolocationlevel5id', models.CharField(max_length=255, null=True, db_column='COOLocationLevel5ID', blank=True)),
                ('vulnerabilitycode', models.CharField(max_length=255, null=True, db_column='VulnerabilityCode', blank=True)),
                ('vulnerabilitydetailscode', models.CharField(max_length=255, null=True, db_column='VulnerabilityDetailsCode', blank=True)),
            ],
            options={
                'db_table': 'base_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BDCOAAddress',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('coalocationlevel1id', models.CharField(max_length=255, null=True, db_column='COALocationLevel1ID', blank=True)),
                ('coalocationlevel2id', models.CharField(max_length=255, null=True, db_column='COALocationLevel2ID', blank=True)),
                ('coalocationlevel3id', models.CharField(max_length=255, null=True, db_column='COALocationLevel3ID', blank=True)),
                ('coalocationlevel4id', models.CharField(max_length=255, null=True, db_column='COALocationLevel4ID', blank=True)),
                ('coalocationlevel5id', models.CharField(max_length=255, null=True, db_column='COALocationLevel5ID', blank=True)),
                ('fkindividualguid', models.ForeignKey(to='dwh_data.BaseData')),
            ],
            options={
                'db_table': 't_coa_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BDCOOAddress',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('coolocationlevel1id', models.CharField(max_length=255, null=True, db_column='COOLocationLevel1ID', blank=True)),
                ('coolocationlevel2id', models.CharField(max_length=255, null=True, db_column='COOLocationLevel2ID', blank=True)),
                ('coolocationlevel3id', models.CharField(max_length=255, null=True, db_column='COOLocationLevel3ID', blank=True)),
                ('coolocationlevel4id', models.CharField(max_length=255, null=True, db_column='COOLocationLevel4ID', blank=True)),
                ('coolocationlevel5id', models.CharField(max_length=255, null=True, db_column='COOLocationLevel5ID', blank=True)),
                ('fkindividualguid', models.ForeignKey(to='dwh_data.BaseData')),
            ],
            options={
                'db_table': 't_coo_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BDGroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('processinggrouptypecode', models.CharField(max_length=255, null=True, db_column='ProcessingGroupTypeCode', blank=True)),
                ('processinggroupnumber', models.CharField(max_length=255, null=True, db_column='ProcessingGroupNumber', blank=True)),
                ('currentrationcardnumber', models.CharField(max_length=255, null=True, db_column='CurrentRationCardNumber', blank=True)),
                ('processinggroupfilenumber', models.CharField(max_length=255, null=True, db_column='ProcessingGroupFileNumber', blank=True)),
                ('processinggroupsize', models.CharField(max_length=255, null=True, db_column='ProcessingGroupSize', blank=True)),
                ('processinggroupstatuscode', models.CharField(max_length=255, null=True, db_column='ProcessingGroupStatusCode', blank=True)),
                ('processgroupstatusdate', models.CharField(max_length=255, null=True, db_column='ProcessGroupStatusDate', blank=True)),
                ('processinggroupregistrationdate', models.CharField(max_length=255, null=True, db_column='ProcessingGroupRegistrationDate', blank=True)),
                ('individualsequencenumber', models.CharField(max_length=255, null=True, db_column='IndividualSequenceNumber', blank=True)),
                ('fkindividualguid', models.ForeignKey(to='dwh_data.BaseData')),
            ],
            options={
                'db_table': 't_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BDVulnerability',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('vulnerabilitycode', models.CharField(max_length=255, null=True, db_column='VulnerabilityCode', blank=True)),
                ('vulnerabilitydetailscode', models.CharField(max_length=255, null=True, db_column='VulnerabilityDetailsCode', blank=True)),
                ('fkindividualguid', models.ForeignKey(to='dwh_data.BaseData')),
            ],
            options={
                'db_table': 't_vuln_status',
                'managed': True,
            },
        ),
    ]
